name: Build Signed APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Исправляем права на всякий случай
      - name: Fix permissions
        run: sudo chmod -R 777 .

      - name: Build with Buildozer
        # Используем этот экшен, он лучше работает с правами, чем сырой Docker
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android release
          buildozer_version: master
        env:
          # Пароли
          P4A_RELEASE_KEYSTORE: my-release-key.jks
          P4A_RELEASE_KEYSTORE_PASSWD: "58Dasha58."
          P4A_RELEASE_KEYALIAS: my-key-alias
          P4A_RELEASE_KEYALIAS_PASSWD: "58Dasha58."

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
