name: Build Signed APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android release
          buildozer_version: stable
        env:
          # Укажите здесь пароль, который вы вводили при создании ключа
          P4A_RELEASE_KEYSTORE: my-release-key.jks
          P4A_RELEASE_KEYSTORE_PASSWD: "ВАШ_ПАРОЛЬ"
          P4A_RELEASE_KEYALIAS: my-key-alias
          P4A_RELEASE_KEYALIAS_PASSWD: "ВАШ_ПАРОЛЬ"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
