name: Build Signed APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04  # Используем старую Ubuntu, где нет проблем с externally-managed
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Подготовка окружения (Python + Java)
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv

      # 2. Восстановление прав (на всякий случай)
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER .

      # 3. Сборка APK
      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          # Передаем пароли через переменные окружения
          export P4A_RELEASE_KEYSTORE=my-release-key.jks
          export P4A_RELEASE_KEYSTORE_PASSWD="58Dasha58."
          export P4A_RELEASE_KEYALIAS=my-key-alias
          export P4A_RELEASE_KEYALIAS_PASSWD="58Dasha58."
          
          # Запускаем сборку
          buildozer android release
        
      # 4. Загрузка результата
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
