name: Build Signed APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer Docker
        uses: docker://kivy/buildozer:latest
        with:
          # ВАЖНО: Убрали слово "buildozer", оставили только аргументы
          args: android release
        env:
          # Пароли
          P4A_RELEASE_KEYSTORE: my-release-key.jks
          P4A_RELEASE_KEYSTORE_PASSWD: "58Dasha58."
          P4A_RELEASE_KEYALIAS: my-key-alias
          P4A_RELEASE_KEYALIAS_PASSWD: "58Dasha58."
          # Права
          USER: root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
