name: Build Signed APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          # Добавил libtool-bin
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-venv \
            git zip unzip openjdk-17-jdk autoconf libtool libtool-bin pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev

      - name: Install Buildozer in Venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install git+https://github.com/kivy/buildozer.git@master
          pip install cython==0.29.33

      - name: Build APK
        run: |
          source venv/bin/activate
          sudo chmod -R 777 .
          
          export P4A_RELEASE_KEYSTORE=my-release-key.jks
          export P4A_RELEASE_KEYSTORE_PASSWD="58Dasha58."
          export P4A_RELEASE_KEYALIAS=my-key-alias
          export P4A_RELEASE_KEYALIAS_PASSWD="58Dasha58."
          
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
