name: Build Signed APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer Docker
        # Мы используем официальный контейнер, где всё уже настроено
        uses: docker://kivy/buildozer:latest
        with:
          args: buildozer android release
        env:
          # Пароли для подписи
          P4A_RELEASE_KEYSTORE: my-release-key.jks
          P4A_RELEASE_KEYSTORE_PASSWD: "58Dasha58."
          P4A_RELEASE_KEYALIAS: my-key-alias
          P4A_RELEASE_KEYALIAS_PASSWD: "58Dasha58."
          # Права доступа (чтобы не было ошибки пользователя)
          USER: root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
