name: Build Signed APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          # 1. Обновляем списки пакетов
          sudo apt-get update
          
          # 2. Ставим системные зависимости (включая pip)
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
          # 3. Обновляем сам pip (чтобы он стал свежим и умным)
          pip3 install --upgrade pip
          
          # 4. Теперь ставим Buildozer (уже без флага break-system, но с флагом --user)
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER .

      - name: Build APK
        run: |
          # Добавляем путь к локально установленным программам (buildozer)
          export PATH=$PATH:~/.local/bin
          
          # Пароли
          export P4A_RELEASE_KEYSTORE=my-release-key.jks
          export P4A_RELEASE_KEYSTORE_PASSWD="58Dasha58."
          export P4A_RELEASE_KEYALIAS=my-key-alias
          export P4A_RELEASE_KEYALIAS_PASSWD="58Dasha58."
          
          # Запуск
          buildozer android release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-signed-app
          path: bin/*.apk
